set more values in carstate that are used by interface
this fixes this error:
Process controlsd:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./manager.py", line 147, in launcher
    mod.main(gctx)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 537, in main
    controlsd_thread(gctx, 100)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 505, in controlsd_thread
    overtemp, free_space)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 51, in data_sample
    CS = CI.update(CC)
  File "/data/openpilot/selfdrive/car/chrysler/interface.py", line 151, in update
    ret.wheelSpeeds.fl = self.CS.v_wheel_fl
AttributeError: 'CarState' object has no attribute 'v_wheel_fl'